### ISSUE TITLE
Build on linux

### ISSUE THREAD

**Issue by elliottwilliams** [propershark/timetable_cpp#13]
For deployment, we need a way of building timetable on linux. We could insist on using clang, however, I've been playing with installing clang on our server and it's not as simple as an `apt get` (currenly having problems with the linker and `libstdc++` vs `libc++`).

I think it'd make the most sense to just change a few clang-specific sections of the code, making timetable more portable. For example, I'm seeing this error when I try to compile:

```
src/datetime/resolve.cc: In member function ‘void DateTime::resolve()’:
src/datetime/resolve.cc:23:3: sorry, unimplemented: non-trivial designated initializers not supported
   };
   ^
src/datetime/resolve.cc:23:3: sorry, unimplemented: non-trivial designated initializers not supported
src/datetime/resolve.cc:23:3: sorry, unimplemented: non-trivial designated initializers not supported
src/datetime/resolve.cc:23:3: sorry, unimplemented: non-trivial designated initializers not supported
src/datetime/resolve.cc:23:3: sorry, unimplemented: non-trivial designated initializers not supported
src/datetime/resolve.cc:23:3: sorry, unimplemented: non-trivial designated initializers not supported
src/datetime/resolve.cc:23:3: sorry, unimplemented: non-trivial designated initializers not supported
src/datetime/resolve.cc:23:3: warning: missing initializer for member ‘tm::tm_yday’ [-Wmissing-field-initializers]
src/datetime/resolve.cc:23:3: warning: missing initializer for member ‘tm::tm_isdst’ [-Wmissing-field-initializers]
src/datetime/resolve.cc:23:3: warning: missing initializer for member ‘tm::tm_gmtoff’ [-Wmissing-field-initializers]
src/datetime/resolve.cc:23:3: warning: missing initializer for member ‘tm::tm_zone’ [-Wmissing-field-initializers]
```

As it would seem, [gcc doesn't support designated initializers in c++][1], while clang does. I anticipate little adjustments like this will be necessary if you want portability.

[1]: http://stackoverflow.com/questions/18731707/why-does-c11-not-support-designated-initializer-list-as-c99

**Comment by faultyserver** [comment]
Oh gcc, my appreciation of clang only grows stronger.

There were a lot of small bugs that came up when I first tried compiling on linux. They should all be relatively minor (nothing logic-breaking or requiring class refactors). I might turn this into a PR soon to help track changes and errors that come up.

I noticed that the `wamped` dependency also had a few issues compiling on gcc, and I'm not entirely sure how much work will have to go into those to ensure they work the same as they do with clang. Yet another reason to start working on our own version :)

**Comment by elliottwilliams** [comment]
I had already started a branch, so #15 is open for you to work off of.

**Comment by elliottwilliams** [comment]
I've got timetable building on Ubuntu 16.04 (shark-nyc1.transio.us), having installed clang (yay!) and [libc++](http://libcxx.llvm.org). Closing.

**Comment by elliottwilliams** [comment]
Well, let me back up. Timetable compiles just fine, but on my system I get 

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

after Timetable _receives_ an RPC invocation. Any ideas what might be happening?

**Comment by faultyserver** [comment]
This is on your own linux box or the transio.us server? It could easily be that the transio.us server is _actually_ out of memory (remember that `shark` has crashed multiple times because of that).

At a glance, this seems like something to do with the MsgPack wrapper that `wamped` uses. My only other guess immediately would be something in the [`DateTime` implementation I wrote](https://github.com/propershark/timetable_cpp/blob/c4f19ef62b3d2170dc2691bbce2ba45286a01ad6/include/datetime.h) causing it to fail on parse.

Looking at [the documentation for `std::bad_alloc`](http://en.cppreference.com/w/cpp/memory/new/bad_alloc) it seems to only be thrown when `new` fails, which _should_ be exceptionally rare. Have you encountered this consistently? Or just once or twice?

**Comment by elliottwilliams** [comment]
> This is on your own linux box or the transio.us server? It could easily be that the transio.us server is actually out of memory (remember that shark has crashed multiple times because of that).

Yep, this is transio.us. I increased its RAM to 1G and added 2G of swap, so I'd be surprised to see this happening, but I will resize again in a bit and see if I can reproduce.

> Have you encountered this consistently? Or just once or twice?

Consistently.

When I get a chance to work on it again I'll look at the core dumps and may try profiling timetable's memory usage. Regardless, happy to get it building!

**Comment by faultyserver** [comment]
Interesting. Timetable takes ~250MB of RAM with the CityBus GTFS loaded. Let me know how that goes.

**Comment by elliottwilliams** [comment]
This was fixed by https://github.com/propershark/timetable_cpp/commit/db26170a54b4e78ff5f21987870f435a54e041c1
