### ISSUE TITLE
Optional csv fields

### ISSUE THREAD

**Issue by elliottwilliams** [propershark/timetable_cpp#19]
Does timetable support nullability / default values for optional fields in the GTFS spec? If not, what needs to be done to support it?

For context, I'm playing with BART and SFMTA's GTFS feeds. Both feeds cause timetable to crash while parsing the `pickup_type` field from `stop_times.txt`:

```
Reading trips
Reading routes
Reading stops
Parsing stop times
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: stoi: no conversion
Process 11532 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fffbbc6ed42 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fffbbc6ed42 <+10>: jae    0x7fffbbc6ed4c            ; <+20>
    0x7fffbbc6ed44 <+12>: movq   %rax, %rdi
    0x7fffbbc6ed47 <+15>: jmp    0x7fffbbc67caf            ; cerror_nocancel
    0x7fffbbc6ed4c <+20>: retq
(lldb) up 10
frame #10: 0x00000001000ac279 timetable`gtfs::csv_parser<gtfs::stop_time>::_parse_line(this=0x0000000100118270, line="01SFO10SUN,08:00:00,08:00:00,LAFY,1,Millbrae,,,,1\r") at csv_parser.h:77
   74             switch(mapper.type) {
   75               case tBOOL:   mapper.apply(inst, column == "1");     break;
   76               case tDOUBLE: mapper.apply(inst, std::stod(column)); break;
-> 77               case tINT:    mapper.apply(inst, std::stoi(column)); break;
   78               case tSTRING: mapper.apply(inst, column);            break;
   79               default:      break;
   80             }
```

Per [the spec](https://developers.google.com/transit/gtfs/reference/stop_times-file), `pickup_type` is optional and defaults to `0`.

**Comment by faultyserver** [comment]
No. Currently, timetable examines the header field of the CSV and expects a value for each of those fields in every row.

Adding default values shouldn't be too difficult. The field mapping is done [in `include/gtfs/source.h`](https://github.com/propershark/timetable_cpp/blob/07353c78757482f9cd1970cce9061b2cf8d8d39b/include/gtfs/source.h#L118), and [`make_field_mapper`](https://github.com/propershark/timetable_cpp/blob/master/include/gtfs/field_mapper.h#L27) could be supplemented to include a default value for a field.

I hadn't noticed the default values that the spec gives, so I wasn't sure if that was something that should be supported. If it's in the spec, though, it should definitely be added.
